name: Docker Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  docker-backend:
    name: Docker Publish Backend
    uses: minisource/.github/.github/workflows/docker-release.yml@main
    with:
      image-name: minisource/auth-backend
      dockerfile-path: backend/Dockerfile
      build-context: .
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-frontend:
    name: Docker Publish Frontend
    uses: minisource/.github/.github/workflows/docker-release.yml@main
    with:
      image-name: minisource/auth-frontend
      dockerfile-path: front/Dockerfile
      build-context: .
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
